/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuitesRouteImport } from './routes/suites'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as IndexRouteImport } from './routes/index'

const SuitesRoute = SuitesRouteImport.update({
  id: '/suites',
  path: '/suites',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/facilities': typeof FacilitiesRoute
  '/suites': typeof SuitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/facilities': typeof FacilitiesRoute
  '/suites': typeof SuitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/facilities': typeof FacilitiesRoute
  '/suites': typeof SuitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/facilities' | '/suites'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/facilities' | '/suites'
  id: '__root__' | '/' | '/facilities' | '/suites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FacilitiesRoute: typeof FacilitiesRoute
  SuitesRoute: typeof SuitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suites': {
      id: '/suites'
      path: '/suites'
      fullPath: '/suites'
      preLoaderRoute: typeof SuitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FacilitiesRoute: FacilitiesRoute,
  SuitesRoute: SuitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
